// console.log("hi");
const friends = ["sree", "ram", "mich"];
// console.log(friends);
// const years = new Array(1234, 2345, 1345, 2345);
// console.log(friends[0]);
// console.log(friends[1]);
// console.log(friends[2]);
// console.log(friends[1]);
console.log(friends.length);
console.log(friends[friends.length - 1]);
friends[2] = "jay";
console.log(friends);
console.log(friends);
const friend = ["sree", "ram", "mich"];
friend.push("sreeram");
console.log(friend);
friend.unshift("john");
console.log(friend);
friend.pop();
friend.pop();
console.log(friend);
friend.unshift("srre");
console.log(friend);

friend.push("srhe");
console.log(friend);
friend.shift("gret");
console.log(friend);
console.log(friend.indexOf("rm"));
console.log(friend);
console.log(friend.indexOf("sree"));
